version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Scores.txt:/Scores.txt  
    restart: always
    container_name: flask-app-container
